In [125]:
import seaborn as sns
import matplotlib.pyplot as plt

In [126]:
import pandas as pd
import numpy as np

test = pd.read_csv('../datasets/bike_test.csv')
train = pd.read_csv('../datasets/bike_train.csv')

In [127]:
train['datetime'] = train['datetime'].apply(pd.to_datetime)
test['datetime'] = test['datetime'].apply(pd.to_datetime)

In [128]:
test['year'] = test['datetime'].apply(lambda x : x.year )
test['month'] = test['datetime'].apply(lambda x : x.month )
test['day'] = test['datetime'].apply(lambda x : x.day )
test['hour'] = test['datetime'].apply(lambda x : x.hour )

In [129]:
train['year'] = train['datetime'].apply(lambda x : x.year)
train['month'] = train['datetime'].apply(lambda x : x.month)
train['day'] = train['datetime'].apply(lambda x : x.day)
train['hour'] = train['datetime'].apply(lambda x : x.hour)

In [131]:
from sklearn.model_selection import train_test_split

X = train.drop('count', axis=1)
y = train['count']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=0)

In [132]:
y_train

8620     280
8985     832
6171     205
6473      54
10877    237
        ...
4859     153
3264     188
9845     617
10799    132
2732     383
Name: count, Length: 7620, dtype: int64

In [133]:
X_train.drop(['datetime', 'casual', 'registered'], axis=1, inplace=True)
X_test.drop(['datetime', 'casual', 'registered'], axis=1, inplace=True)

In [134]:
train.head(1)

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count,year,month,day,hour
0,2011-01-01,1,0,0,1,9.84,14.395,81,0.0,3,13,16,2011,1,1,0

In [135]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train[['temp', 'atemp', 'humidity', 'windspeed']] = scaler.fit_transform(X_train[['temp', 'atemp', 'humidity', 'windspeed']])
X_test[['temp', 'atemp', 'humidity', 'windspeed']] = scaler.fit_transform(X_test[['temp', 'atemp', 'humidity', 'windspeed']])

In [136]:
from sklearn.linear_model import LinearRegression , Ridge , Lasso , ElasticNet
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error , r2_score , mean_absolute_error 

lr = LinearRegression()
ridge = Ridge()
lasso = Lasso()
ela = ElasticNet(random_state=42)

models = ['LinearRegression' , 'Ridge' , 'Lasso' , 'ElasticNet']
for model in models:
    if model == "LinearRegression":
        estimator = lr
    elif model == "Ridge":
        estimator = ridge
    elif model == "Lasso":
        estimator = lasso
    else :
        estimator = ela
    result = cross_val_score(estimator ,X_train , y_train, cv=5 , scoring='neg_mean_squared_error' )
    avg_rmse = np.mean(np.sqrt(-1 * result))
    print(f'{model}의 rmse의 평균 :{avg_rmse}')
    estimator.fit(X_train , y_train)
    pred = estimator.predict(X_test)

    mse = mean_squared_error(y_test, pred)
    mae = mean_absolute_error(y_test, pred)
    r2score = r2_score(y_test, pred)
    print(f'{model}의 mse : {mse} , mae : {mae}  , r2score : {r2score}')

    print("==================================")

LinearRegression의 rmse의 평균 :142.14899663784632
LinearRegression의 mse : 19857.803964257764 , mae : 105.5709259568066  , r2score : 0.38851790711840306
==================================
Ridge의 rmse의 평균 :142.1486480175424
Ridge의 mse : 19857.93831561375 , mae : 105.56923764957064  , r2score : 0.38851377003212273
==================================
Lasso의 rmse의 평균 :142.18283236316773
Lasso의 mse : 19871.839886374266 , mae : 105.19860026822055  , r2score : 0.38808569844886587
==================================
ElasticNet의 rmse의 평균 :145.68473804489392
ElasticNet의 mse : 20996.342603765803 , mae : 106.75380920061558  , r2score : 0.35345884462760446
==================================

In [122]:
y_train

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,year,month,day,hour
8620,2012-08-01 13:00:00,3,0,1,1,32.80,37.120,52,11.0014,59,221,2012,8,1,13
8985,2012-08-16 18:00:00,3,0,1,1,32.80,35.605,36,0.0000,109,723,2012,8,16,18
6171,2012-02-13 09:00:00,1,0,1,1,4.92,6.820,50,12.9980,7,198,2012,2,13,9
6473,2012-03-06 23:00:00,1,0,1,1,11.48,13.635,61,15.0013,3,51,2012,3,6,23
10877,2012-12-19 15:00:00,4,0,1,1,17.22,21.210,50,19.0012,28,209,2012,12,19,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4859,2011-11-15 13:00:00,4,0,1,3,22.14,25.760,60,15.0013,21,132,2011,11,15,13
3264,2011-08-05 22:00:00,3,0,1,1,28.70,32.575,65,15.0013,51,137,2011,8,5,22
9845,2012-10-14 14:00:00,4,0,0,1,27.06,31.060,39,27.9993,249,368,2012,10,14,14
10799,2012-12-16 09:00:00,4,0,0,2,14.76,17.425,87,8.9981,19,113,2012,12,16,9
2732,2011-07-02 18:00:00,3,0,0,1,33.62,35.605,30,19.0012,193,190,2011,7,2,18

In [ ]:
# from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
# from sklearn.model_selection import cross_val_score
# from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# models = [LinearRegression, Ridge, Lasso, ElasticNet]

# for model in models:
#     if model == LinearRegression:
#         estimator = LinearRegression()
#     elif model == Ridge:
#         estimator = Ridge()
#     elif model == Lasso:
#         estimator = Lasso()
#     elif model == ElasticNet:
#         estimator = ElasticNet(random_state=42)
    
#     neg_mse_scores = cross_val_score(estimator, X_train, y_train, cv=5, 
#                              scoring='neg_mean_squared_error')
#     avg_rmse = np.mean(np.sqrt(-1 * neg_mse_scores))

#     print(f'{model}의  rmse의 평균 : {avg_rmse}')
#     estimator.fit(X_train, y_train)
#     pred = estimator.predict(X_test)

#     mse = mean_squared_error(y_test, pred)
#     mae = mean_absolute_error(y_test, pred)
#     r2score = r2_score(y_test, pred)
#     print(f'mse : {mse}, mae : {mae}, r2_score : {r2score}')
#     print('================================================')

ValueError:
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\User\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\User\anaconda3\Lib\site-packages\sklearn\linear_model\_base.py", line 648, in fit
    X, y = self._validate_data(
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py", line 584, in _validate_data
    X, y = check_X_y(X, y, **check_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 1122, in check_X_y
    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric, estimator=estimator)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 1132, in _check_y
    y = check_array(
        ^^^^^^^^^^^^
  File "c:\Users\User\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 778, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in result_type
TypeError: The DType <class 'numpy.dtype[datetime64]'> could not be promoted by <class 'numpy.dtype[float64]'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtype[datetime64]'>, <class 'numpy.dtype[int64]'>, <class 'numpy.dtype[int64]'>, <class 'numpy.dtype[int64]'>, <class 'numpy.dtype[int64]'>, <class 'numpy.dtype[float64]'>, <class 'numpy.dtype[float64]'>, <class 'numpy.dtype[int64]'>, <class 'numpy.dtype[float64]'>, <class 'numpy.dtype[int64]'>, <class 'numpy.dtype[int64]'>, <class 'numpy.dtype[int64]'>, <class 'numpy.dtype[int64]'>, <class 'numpy.dtype[int64]'>, <class 'numpy.dtype[int64]'>)